services:
  auth-service:
    build: ./auth-service
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}

      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: ${AUTH_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_DB_PASSWORD}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      - broker
      - auth-db
      - redis

  user-service:
    build: ./user-service
    restart: unless-stopped
    ports:
      - "9091:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}

      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
      SPRING_DATASOURCE_USERNAME: ${USER_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_DB_PASSWORD}
    depends_on:
      - broker
      - user-db

  discord-bot-service:
    build: ./discord-bot-service
    restart: unless-stopped
    ports:
      - "9094:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - broker
      - redis

  account-linking-service:
    build: ./account-linking-service
    restart: unless-stopped
    ports:
      - "9093:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_DATASOURCE_URL: jdbc:postgresql://linking-db:5432/linking_db
      SPRING_DATASOURCE_USERNAME: ${LINK_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${LINK_DB_PASSWORD}
    depends_on:
      - broker
      - redis
      - linking-db

  broker:
    image: apache/kafka:4.2.0
    restart: unless-stopped
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  auth-db:
    image: postgres:16
    container_name: auth_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  user-db:
    image: postgres:16
    container_name: user_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: user_db
    ports:
      - "5434:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data

  linking-db:
    image: postgres:16
    container_name: linking_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${LINK_DB_USER}
      POSTGRES_PASSWORD: ${LINK_DB_PASSWORD}
      POSTGRES_DB: linking_db
    ports:
      - "5435:5432"
    volumes:
      - linking_pgdata:/var/lib/postgresql/data

volumes:
  redis:
  auth_pgdata:
  user_pgdata:
  linking_pgdata: