services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: connectme_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: auth-group
      TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/connectme_db
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - broker
      - db

  user-service:
    build: ./user-service
    restart: unless-stopped
    ports:
      - "9091:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: user-group
      TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/connectme_db
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - broker
      - db

  discord-bot-service:
    build: ./discord-bot-service
    restart: unless-stopped
    ports:
      - "9094:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: bot-group
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - broker
      - redis

  account-linking-service:
    build: ./account-linking-service
    restart: unless-stopped
    ports:
      - "9093:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: linking-group
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/connectme_db
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - broker
      - redis
      - db

  broker:
    image: apache/kafka:4.2.0
    restart: unless-stopped
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"


  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    container_name: redis
    volumes:
      - redis:/data


volumes:
  redis:
  pgdata: